algorithm:
  name: "ppo"
  verbose: 10
  policy:
    name: MlpPolicy
  tensorboard_log: true
  n_steps: 256
  learning_rate:
    type: linear
    initial_value: 2.5e-4
    final_value: 1.0e-5
    final_point: 0.2

env:
  name: "CartPole-v1"
  n_envs: 8
  frame_stack:
    n_stack: 4
  normalize:
    precompute: true
    samples: 10000
    norm_reward: false
    norm_obs: true

meta:
  seed: 42
  n_timesteps: 14000
  log_dir: "./logs/Labtest_CartPole"
  save_interval: 4000

search:
  n_timesteps: 8000
  eval_method: "normal"
  n_trials: 4
  sampler: "tpe"
