algorithm:
  name: "ppo"
  verbose: 10
  policy:
    name: MlpPolicy
  tensorboard_log: true

env:
  name: "CartPole-v1"
  frame_stack:
    n_stack: 4
  multiprocessing: false
  normalize:
    precompute: true
    samples: 10000
    norm_reward: false
    norm_obs: true

meta:
  seed: 42
  n_timesteps: 14000
  log_dir: "./logs/Labtest_CartPole"
  save_interval: 4000

search:
  n_timesteps: 12000
  eval_method: "normal"
  n_trials: 25
  sampler: "tpe"
  pruner:
    method: "halving"
    min_resource: "auto"
  algorithm:
    policy:
      activation_fn:
        sample: true
        method: "categorical"
        choices: [ torch.nn.SELU, torch.nn.ReLU ]
  env:
    n_envs:
      sample: true
      method: "categorical"
      choices: [ 2, 4, 8 ]
